package(
    default_visibility = ["//src:__subpackages__"],
)

android_library(
    name = "le_activity",
    srcs = [
        "MainActivity.kt",
    ],
    manifest = "Manifests/AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)